checks:
    php:
        code_rating: true
        duplication: true

before_commands:
    - 'composer install --no-interaction --no-scripts'

build:
    environment:
        php:
            version: 5.6
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'php-clover'
